services:
  - type: web
    name: sistema-elvis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://equahome:UotA3zOqWWmzZJzK6bLWD7ksV4Bg2RmK@dpg-d8ooagurnols73db7btg-a/equahome?options=-csearch_path%3Delvis

